erstellt: false
message_str: "Einleitung:\n\nLandratsamt Ortenaukreis\nHerrn Franz Konrad\nSachbearbeiter\n\
  \nReparatur Ihres Fachwerkhauses in Neuried, Lange Stra\xDFe 12\n\nSehr geehrter\
  \ Herr Konrad,\n\nTenor:\n\nEs wird angeordnet, dass Sie Ihr Fachwerkhaus mit Biberschwanzdachziegeln\
  \ reparieren m\xFCssen.\n\nDie Anordnung der sofortigen Vollziehung dieser Ma\xDF\
  nahme wird hiermit angeordnet.\n\nBegr\xFCndung:\n\nSie sind als Forstrat zusammen\
  \ mit Ihrem Bruder, dem Studenten Georg Konrad, Eigent\xFCmer des o.g. Fachwerkhauses.\
  \ Ihr Haus stammt aus dem Jahre 1865. Das Haus hat die f\xFCr die damalige Bauweise\
  \ charakteristischen Wetterd\xE4cher sowie die typischen, vorragenden Balkenk\xF6\
  pfe an den Erdgeschossbalken. Es ist mit den seinerzeit \xFCblichen Biberschwanz-Dachziegeln\
  \ gedeckt. Das Fachwerkhaus geh\xF6rt zu den wenigen voll erhaltenen Exemplaren\
  \ seiner Art am Oberrhein.\n\nDurch einen Sturm wurden ca. 50 Biberschwanz-Dachziegel\
  \ abgedeckt.\n\nDie Reparaturanordnung st\xFCtzt sich auf \xA7 1 Abs. 1 in Verbindung\
  \ mit \xA7 7 Abs. 1 Denkmalschutzgesetz (DSchG). Danach k\xF6nnen wir Ma\xDFnahmen\
  \ anordnen, wenn ein Kulturdenkmal gef\xE4hrdet ist.\n\nDas Fachwerkhaus ist ein\
  \ Kulturdenkmal. Es besteht n\xE4mlich nach \xA7 2 Abs. 1 DSchG an dem Fachwerkhaus\
  \ ein \xF6ffentliches Erhaltungsinteresse aus heimatgeschichtlichen Gr\xFCnden.\
  \ Das Haus stammt aus dem Jahr 1865 und hat die f\xFCr die damalige Bauweise charakteristischen\
  \ Wetterd\xE4cher sowie die typischen, vorragenden Balkenk\xF6pfe an den Erdgeschossbalken\
  \ und ist mit den seinerzeit \xFCblichen Biberschwanz-Dachziegeln gedeckt.\n\nDas\
  \ Kulturdenkmal ist gef\xE4hrdet, da durch das beeintr\xE4chtigte Erscheinungsbild\
  \ bereits ein Schaden entstanden ist. Der Sturm hat ca. 50 Biberschwanz-Dachziegel\
  \ abgedeckt.\n\nSie sind verpflichtet, die Reparatur durchzuf\xFChren.\n\nDas ergibt\
  \ sich aus \xA7 7 Polizeigesetz (PolG), da Sie Eigent\xFCmer des Fachwerkhauses\
  \ sind, von dem eine Gef\xE4hrdung des Denkmals ausgeht.\n\nEbenfalls nach denselben\
  \ Vorschriften verpflichtet, ist Ihr Bruder Georg Konrad, da dieser ebenfalls Eigent\xFC\
  mer ist. Als Forstrat sind Sie leistungsf\xE4higer als Ihr Bruder Georg und sind\
  \ deshalb verpflichtet, die Kosten zu tragen.\n\nUns ist hier Ermessen einger\xE4\
  umt, wobei wir als gesetzliche Grenze im Sinne von \xA7 40 Landesverwaltungsverfahrensgesetz\
  \ die Verh\xE4ltnism\xE4\xDFigkeit nach Art. 20 Abs. 3 GG beachtet haben.\n\nDie\
  \ Anordnung das Dach mit Biberschwanz-Dachziegeln zu reparieren ist angemessen,\
  \ um die Ansehnlichkeit des Denkmals herbeizuf\xFChren. Diese Anordnung ist auch\
  \ erforderlich, da es kein milderes gleichgeeignetes Mittel gibt. Ethanitplatten\
  \ w\xE4ren zwar kosteng\xFCnstiger, k\xF6nnten aber nicht die Ansehnlichkeit wieder\
  \ herstellen. Schlie\xDFlich ist die Reparaturanordnung auch angemessen.\n\nIhr\
  \ Nachteil steht nicht au\xDFer Verh\xE4ltnis zu den Vorteilen f\xFCr die Allgemeinheit.\
  \ Das Interesse am Erhalt des Denkmals gewichtet durch Art. 3 C Landes Verfassung\
  \ \xFCberwiegt Ihr Interesse bez\xFCglich finanzieller Belastung und der Eigentumsrechte\
  \ gewichtet durch Art. 14 GG.\n\nDie Durchf\xFChrung der Ma\xDFnahme ist Ihnen auch\
  \ ohne die Mitwirkung Ihres Bruders Georg m\xF6glich ist. An sich h\xE4tte er als\
  \ Miterbe nach \xA7 2038 BGB mitzubestimmen, weil es sich bei der Reparaturanordnung\
  \ jedoch um eine Notma\xDFnahme handelt, ist diese Mitbestimmung nicht notwendig.\
  \ Im Hinblick auf den Verkaufswert des Fachwerkhauses ist es als Notma\xDFnahme\
  \ wirtschaftlich vern\xFCnftig das Dach mit Biberschwanz-Dachziegeln zu reparieren.\n\
  \nAls Rechtsgrundlage f\xFCr die Anordnung dient \xA7 80 Abs. 2 Satz 1 Nr. 4. Landesverwaltungsverfahrensgesetz.\n\
  \nRechtsbehelfsbelehrung:\n\nGegen die Dachdeckungsanordnung k\xF6nnen Sie innerhalb\
  \ eines Monats nach Bekanntgabe bei dem Landratsamt Ortenaukreis, Badstra\xDFe 22,\
  \ 77652 Offenburg Widerspruch einlegen. (\xA737 (6) LVwVfG (\xA770 VwGO))\n\nGegen\
  \ die Anordnung der sofortigen Vollziehung k\xF6nnen Sie den Antrag auf Wiederherstellung\
  \ der aufschiebenden Wirkung beim Verwaltungsgericht Freiburg, Herbstburgerstra\xDF\
  e 115, 79104 Freiburg stellen. (\xA7 80 Abs. 5 VwGO)\n\nUnterschrift mit Gru\xDF\
  formel:\n\nMit freundlichen Gr\xFC\xDFen,\n\nLisa Brunzel"
