erstellt: true
message_str: "Einleitung:\nSehr geehrter Herr Graeter,\n\nSie haben einen Antrag auf\
  \ Erlaubnis zur Betreibung einer Musikkneipe in den leer stehenden R\xE4umen der\
  \ ehemaligen Gastst\xE4tte \"Walfisch\" in der Hauptstra\xDFe in Kehl gestellt.\n\
  \nBei der Durchsicht der Unterlagen wurden jedoch M\xE4ngel festgestellt, die eine\
  \ Erlaubniserteilung fraglich machen.\n\nTenor:\nDie Stadt Kehl versagt Ihnen gem\xE4\
  \xDF \xA7 5 GastG die Erlaubnis zur Betreibung einer Musikkneipe in den R\xE4umlichkeiten\
  \ der ehemaligen Gastst\xE4tte \"Walfisch\" in der Hauptstra\xDFe in Kehl.\n\nBegr\xFC\
  ndung:\nGem\xE4\xDF \xA7 2 GastG besteht eine Erlaubnispflicht f\xFCr die Betreibung\
  \ einer Musikkneipe, in der Speisen und Getr\xE4nke serviert werden.\n\nBei der\
  \ Pr\xFCfung Ihres Antrags wurden jedoch M\xE4ngel festgestellt, die eine Erlaubniserteilung\
  \ nicht rechtfertigen.\n\nZum einen fehlt die Bescheinigung \xFCber lebensmittelrechtliche\
  \ Kenntnisse, die gem\xE4\xDF \xA7 4 Abs.\n\n1 Nr.\n\n3 GastG eine Voraussetzung\
  \ f\xFCr die Erlaubniserteilung darstellt.\n\nZum anderen erf\xFCllen die Herrentoiletten\
  \ nicht die bauordnungsrechtlichen Anforderungen gem\xE4\xDF \xA7 3 Abs.\n\n1 GastG.\n\
  \nEs m\xFCssen nach entsprechenden Kapazit\xE4tsberechnungen drei Urinale vorhanden\
  \ sein, jedoch wurden bei der Besichtigung der R\xE4umlichkeiten nur zwei Urinale\
  \ registriert.\n\nDes Weiteren ist zu bef\xFCrchten, dass es aufgrund der Betreibung\
  \ einer Musikkneipe zu L\xE4rmbel\xE4stigungen in der Umgebung kommen wird, was\
  \ gem\xE4\xDF \xA7 5 Abs.\n\n1 Nr.\n\n2 GastG ein Versagungsgrund darstellt.\n\n\
  Die Stadt Kehl hat gem\xE4\xDF \xA7 5 GastG ein Ermessen, das nach \xA7 40 LVwVfG\
  \ ausge\xFCbt wird.\n\nDie Erlaubnis kann versagt werden, wenn die Voraussetzungen\
  \ des \xA7 4 GastG nicht erf\xFCllt sind.\n\nDie Stadt Kehl hat aufgrund der genannten\
  \ M\xE4ngel und Versagungsgr\xFCnde von ihrem Ermessen Gebrauch gemacht und die\
  \ Erlaubnis versagt.\n\nRechtsbehelfsbelehrung:\nGegen diesen Bescheid k\xF6nnen\
  \ Sie innerhalb eines Monats nach Bekanntgabe Widerspruch einlegen (\xA7 70 VwGO).\n\
  \nDer Widerspruch ist schriftlich oder zur Niederschrift bei der Stadt Kehl, Hauptstra\xDF\
  e 1, 77694 Kehl, einzulegen.\n\nUnterschrift mit Gru\xDFformel:\nMit freundlichen\
  \ Gr\xFC\xDFen\n[Unterschrift]"
