chatHist:
- init
erstellt: false
message_str: "Landratsamt Kehl\nHerrn Michael Graeter\nHauptstra\xDFe 123\n77694 Kehl\n\
  \nBetreff: Erlaubnis f\xFCr Betrieb einer Musikkneipe in den leer stehenden R\xE4\
  umen der ehemaligen Gastst\xE4tte \"Walfisch\" in Kehl\n\nSehr geehrter Herr Graeter,\n\
  \nnach Pr\xFCfung Ihres Antrags auf Erlaubnis f\xFCr den Betrieb einer Musikkneipe\
  \ in den leer stehenden R\xE4umen der ehemaligen Gastst\xE4tte \"Walfisch\" in Kehl\
  \ teilen wir Ihnen folgenden Bescheid mit:\n\nTenor:\nDie Erlaubnis f\xFCr den Betrieb\
  \ einer Musikkneipe in den leer stehenden R\xE4umen der ehemaligen Gastst\xE4tte\
  \ \"Walfisch\" in Kehl wird unter folgenden Auflagen erteilt:\n\n1. Sie m\xFCssen\
  \ eine Bescheinigung \xFCber lebensmittelrechtliche Kenntnisse gem\xE4\xDF \xA7\
  \ 4 GastG vorlegen.\n2. Die bauordnungsrechtlichen Voraussetzungen m\xFCssen erf\xFC\
  llt sein, insbesondere die Anzahl der Urinale auf der Herrentoilette gem\xE4\xDF\
  \ den entsprechenden Kapazit\xE4tsberechnungen.\n3. Sie m\xFCssen sicherstellen,\
  \ dass keine L\xE4rmbel\xE4stigung in der Umgebung entsteht, die gem\xE4\xDF \xA7\
  \ 5 GastG zu ber\xFCcksichtigen ist.\n\nBegr\xFCndung:\nGem\xE4\xDF \xA7 2 GastG\
  \ ist der Betrieb einer Musikkneipe erlaubnispflichtig. Die von Ihnen vorgelegten\
  \ Unterlagen erf\xFCllen jedoch nicht alle Voraussetzungen f\xFCr die Erteilung\
  \ der Erlaubnis.\n\nInsbesondere fehlt die Bescheinigung \xFCber lebensmittelrechtliche\
  \ Kenntnisse gem\xE4\xDF \xA7 4 GastG. Diese ist jedoch notwendig, um die Gesundheit\
  \ der G\xE4ste zu sch\xFCtzen.\n\nDes Weiteren m\xFCssen die bauordnungsrechtlichen\
  \ Voraussetzungen erf\xFCllt sein, insbesondere die Anzahl der Urinale auf der Herrentoilette\
  \ gem\xE4\xDF den entsprechenden Kapazit\xE4tsberechnungen.\n\nAu\xDFerdem ist es\
  \ notwendig, L\xE4rmbel\xE4stigungen in der Umgebung zu vermeiden, um die Interessen\
  \ der Anwohner zu wahren.\n\nDie Anordnung der Stadt Kehl ist verh\xE4ltnism\xE4\
  \xDFig und ermessensgerecht, da die genannten Auflagen notwendig sind, um die Gesundheit\
  \ der G\xE4ste zu sch\xFCtzen und die Interessen der Anwohner zu wahren.\n\nAls\
  \ Pflichtiger kommt Michael Graeter in Betracht, da er die Gastst\xE4tte betreiben\
  \ m\xF6chte und somit die Erlaubnis beantragt hat.\n\nDie Stadt Kehl hat gem\xE4\
  \xDF \xA7 5 GastG ein Ermessen bei der Erteilung der Erlaubnis. Die Anordnung der\
  \ Stadt Kehl, die fehlenden lebensmittelrechtlichen Kenntnisse nachzuweisen und\
  \ die bauordnungsrechtlichen Voraussetzungen zu erf\xFCllen, ist verh\xE4ltnism\xE4\
  \xDFig und ermessensgerecht, um die Gesundheit der G\xE4ste und die \xF6ffentliche\
  \ Sicherheit zu gew\xE4hrleisten.\n\nDie Anordnung der Stadt Kehl muss bestimmt\
  \ genug formuliert werden, um den Pflichtigen in die Lage zu versetzen, die Anforderungen\
  \ zu erf\xFCllen.\n\nRechtsbehelfsbelehrung:\nGegen diesen Bescheid kann innerhalb\
  \ eines Monats nach Bekanntgabe Widerspruch eingelegt werden. Der Widerspruch ist\
  \ schriftlich oder zur Niederschrift bei der Stadt Kehl, Hauptstra\xDFe 123, 77694\
  \ Kehl, einzulegen.\n\nMit freundlichen Gr\xFC\xDFen,\n\n[Unterschrift]"
