erstellt: false
message_str: "Landratsamt Ortenaukreis\nHerrn Franz Konrad\nSachbearbeiter\n\nReparatur\
  \ Ihres Fachwerkhauses in Neuried, Lange Stra\xDFe 12\n\nSehr geehrter Herr Konrad,\n\
  \nes ergeht folgender Bescheid:\n\n1. Sie sind verpflichtet, das Dach Ihres Fachwerkhauses\
  \ mit Biberschwanz-Dachziegeln zu reparieren.\n\n2. Wir ordnen die sofortige Vollziehung\
  \ dieser Ma\xDFnahme an.\n\nBegr\xFCndung:\n\nIhr Fachwerkhaus ist ein Kulturdenkmal,\
  \ da es nach \xA7 2 Abs. 1 DSchG eine Sache ist, deren Erhaltung aus heimatgeschichtlichen\
  \ Gr\xFCnden ein \xF6ffentliches Interesse darstellt. Das Haus stammt aus dem Jahr\
  \ 1865 und geh\xF6rt zu den wenigen voll erhaltenen Exemplaren seiner Art am Oberrhein.\
  \ Durch den Sturm wurden ca. 50 Dachziegel abgedeckt, wodurch Regen durch das Dach\
  \ eindringt und das Denkmal gef\xE4hrdet ist.\n\nAls Pflichtige kommen sowohl Sie\
  \ als auch Ihr Bruder Georg Konrad in Betracht. Sie k\xF6nnten pflichtig sein gem\xE4\
  \xDF \xA7 7 Abs. 1 Satz 1 DSchG und \xA7 7 PolG, da Sie Eigent\xFCmer des Fachwerkhauses\
  \ sind, von dessen Zustand eine Gefahr ausgeht. Ihr Bruder Georg Konrad ist ebenfalls\
  \ Eigent\xFCmer und somit nach denselben Vorschriften pflichtig. Letztlich sind\
  \ Sie aufgrund Ihrer h\xF6heren Leistungsf\xE4higkeit der richtige Pflichtige.\n\
  \nDas Landratsamt hat gem\xE4\xDF \xA7 7 DSchG ein Ermessen, das nach \xA7 40 LVwVfG\
  \ ausge\xFCbt wird. Die Anordnung der Reparatur mit Biberschwanz-Dachziegeln ist\
  \ verh\xE4ltnism\xE4\xDFig und ermessensgerecht, da eine kosteng\xFCnstigere Reparatur\
  \ mit Eternitplatten nicht geeignet ist, die Denkmalanforderungen zu erf\xFCllen.\
  \ Der Vorteil f\xFCr die Allgemeinheit durch die Ansehnlichkeit des Denkmals rechtfertigt\
  \ den finanziellen Nachteil f\xFCr den Eigent\xFCmer (Sie).\n\nEs besteht keine\
  \ privatrechtliche Unm\xF6glichkeit, da Sie ohne die Mitwirkung Ihres Bruders Georg\
  \ handeln k\xF6nnen. Eine Ausnahme besteht gem\xE4\xDF \xA7 2038 Abs. 1 Satz 2 Halbsatz\
  \ 2 BGB, wenn die Reparatur als notwendige Erhaltungsma\xDFnahme anzusehen ist.\
  \ Angesichts des h\xF6heren Verkaufswerts des Fachwerkhauses erscheint die Ma\xDF\
  nahme wirtschaftlich vern\xFCnftig.\n\nDie Anordnung ist bestimmt genug formuliert\
  \ gem\xE4\xDF \xA7 37 LVwVfG.\n\nRechtsbehelfsbelehrung:\n\nGegen diesen Bescheid\
  \ k\xF6nnen Sie innerhalb eines Monats nach Bekanntgabe Widerspruch einlegen. Der\
  \ Widerspruch ist schriftlich oder zur Niederschrift beim Landratsamt Ortenaukreis,\
  \ Badstra\xDFe 22, 77652 Offenburg, einzulegen.\n\nMit freundlichen Gr\xFC\xDFen,\n\
  \n[Unterschrift]"
