erstellt: false
message_str: "Landratsamt Ortenaukreis\n\nHerrn Franz Konrad\nLange Stra\xDFe 12\n\
  77743 Neuried\n\nReparatur Ihres Fachwerkhauses in Neuried, Lange Stra\xDFe 12\n\
  \nSehr geehrter Herr Konrad,\n\nes ergeht folgender Bescheid:\n\n1. Sie haben Ihr\
  \ Fachwerkhaus mit Biberschwanz-Dachziegeln zu reparieren.\n\n2. Wir ordnen die\
  \ sofortige Vollziehung dieser Ma\xDFnahme an.\n\nBegr\xFCndung:\n\nSie sind als\
  \ Forstrat zusammen mit Ihrem Bruder, dem Studenten Georg Konrad, Eigent\xFCmer\
  \ des o.g. Fachwerkhauses. Ihr Haus stammt aus dem Jahre 1865. Das Haus hat die\
  \ f\xFCr die damalige Bauweise charakteristischen Wetterd\xE4cher sowie die typischen,\
  \ vorragenden Balkenk\xF6pfe an den Erdgeschossbalken. Es ist mit den seinerzeit\
  \ \xFCblichen Biberschwanz-Dachziegeln gedeckt. Das Fachwerkhaus geh\xF6rt zu den\
  \ wenigen voll erhaltenen Exemplaren seiner Art am Oberrhein.\n\nDurch einen Sturm\
  \ wurden ca. 50 Biberschwanz-Dachziegel abgedeckt.\n\nDie Reparaturanordnung st\xFC\
  tzt sich auf \xA7 1 Abs. 1 in Verbindung mit \xA7 7 Abs. 1 Denkmalschutzgesetz (DSchG).\
  \ Danach k\xF6nnen wir Ma\xDFnahmen anordnen, wenn ein Kulturdenkmal gef\xE4hrdet\
  \ ist.\n\nDas Fachwerkhaus ist ein Kulturdenkmal. Es besteht n\xE4mlich nach \xA7\
  \ 2 Abs. 1 DSchG an dem Fachwerkhaus ein \xF6ffentliches Erhaltungsinteresse aus\
  \ heimatgeschichtlichen Gr\xFCnden. Das Haus stammt aus dem Jahr 1865 und hat die\
  \ f\xFCr die damalige Bauweise charakteristischen Wetterd\xE4cher sowie die typischen,\
  \ vorragenden Balkenk\xF6pfe an den Erdgeschossbalken und ist mit den seinerzeit\
  \ \xFCblichen Biberschwanz-Dachziegeln gedeckt.\n\nDas Kulturdenkmal ist gef\xE4\
  hrdet, da durch das beeintr\xE4chtigte Erscheinungsbild bereits ein Schaden entstanden\
  \ ist. Der Sturm hat ca. 50 Biberschwanz-Dachziegel abgedeckt.\n\nSie sind verpflichtet\
  \ die Reparatur durchzuf\xFChren.\n\nDas ergibt sich aus \xA7 7 Polizeigesetz (PolG),\
  \ da Sie Eigent\xFCmer des Fachwerkhauses sind, von dem eine Gef\xE4hrdung des Denkmals\
  \ ausgeht.\n\nEbenfalls nach denselben Vorschriften verpflichtet, ist Ihr Bruder\
  \ Georg Konrad, da dieser ebenfalls Eigent\xFCmer ist. Als Forstrat sind Sie leistungsf\xE4\
  higer als Ihr Bruder Georg und sind deshalb verpflichtet die Kosten zu tragen.\n\
  \nUns ist hier Ermessen einger\xE4umt, wobei wir als gesetzliche Grenze im Sinne\
  \ von \xA7 40 Landesverwaltungsverfahrensgesetz die Verh\xE4ltnism\xE4\xDFigkeit\
  \ nach Art. 20 Abs. 3 GG beachtet haben.\n\nDie Anordnung das Dach mit Biberschwanz-Dachziegeln\
  \ zu reparieren ist angemessen, die Ansehnlichkeit des Denkmals herbeizuf\xFChren.\
  \ Diese Anordnung ist auch erforderlich, da es kein milderes gleichgeeignetes Mittel\
  \ gibt. Ethanitplatten w\xE4ren zwar kosteng\xFCnstiger, k\xF6nnten aber nicht die\
  \ Ansehnlichkeit wieder herstellen. Schlie\xDFlich ist Reparaturanordnung auch angemessen.\n\
  \nIhr Nachteil steht nicht au\xDFer Verh\xE4ltnis zu den Vorteilen f\xFCr die Allgemeinheit.\
  \ Das Interesse am Erhalt des Denkmals gewichtet durch Art. 3 C Landes Verfassung\
  \ \xFCberwiegt Ihr Interesse bez\xFCglich finanzieller Belastung und der Eigentumsrechte\
  \ gewichtet durch Art. 14 GG.\n\nDie Durchf\xFChrung der Ma\xDFnahme ist Ihnen auch\
  \ ohne die Mitwirkung Ihres Bruders Georg m\xF6glich ist.\n\nAn sich h\xE4tte er\
  \ als Miterbe nach \xA7 2038 BGB mitzubestimmen, weil es sich bei der Reparaturanordnung\
  \ jedoch um eine Notma\xDFnahme handelt, ist diese Mitbestimmung nicht notwendig.\
  \ Im Hinblick auf den Verkaufswert des Fachwerkhauses ist es als Notma\xDFnahme\
  \ wirtschaftlich vern\xFCnftig das Dach mit Biberschwanz-Dachziegeln zu reparieren.\n\
  \nAls Rechtsgrundlage f\xFCr die Anordnung dient \xA7 80 Abs. 2 Satz 1 Nr. 4. Landesverwaltungsverfahrensgesetz.\n\
  \nDie sofortige Vollziehung der Reparaturanordnung kann angeordnet werden, wenn\
  \ ein besonderes \xF6ffentliches Interesse an der baldigen Realisierung der Reparaturanordnung\
  \ besteht und dieses Ihr Interesse an der aufschiebenden Wirkung seines Rechtsbehelfs\
  \ \xFCbersteigt.\n\nEin \xF6ffentliches Interesse besteht darin, dass ohne eine\
  \ Reparatur Regenwasser in das Haus eindringt, welches das Haus besch\xE4digt. Durch\
  \ das Eindringen des Regenwassers kann es zu Schimmelbildung kommen und die Reparaturkosten\
  \ werden sich demnach mit der Zeit erh\xF6hen. In Ihrem Interesse steht Ihre finanzielle\
  \ Lage, welche sich allerdings bei einer Verz\xF6gerung von Reparaturarbeiten, verschlechtern\
  \ w\xFCrde.\n\nRechtsbehelfsbelehrung\n\nGegen die Dachdeckungsanordnung k\xF6nnen\
  \ Sie innerhalb eines Monats nach Bekanntgabe bei dem Landratsamt Ortenaukreis,\
  \ Badstra\xDFe 22, 77652 Offenburg Widerspruch einlegen.\n\n(\xA737 (6) LVwVfG (\xA7\
  70 VwGO))\n\nGegen die Anordnung der sofortigen Vollziehung k\xF6nnen Sie den Antrag\
  \ auf Wiederherstellung der aufschiebenden Wirkung beim Verwaltungsgericht Freiburg,\
  \ Herbstburgerstra\xDFe 115, 79104 Freiburg stellen.\n\n(\xA7 80 Abs. 5 VwGO)\n\n\
  Mit freundlichen Gr\xFC\xDFen\n\n[Unterschrift]"
