erstellt: false
message_str: "Einleitung:\nSehr geehrter Herr Konrad,\n\nnach Pr\xFCfung des Sachverhalts\
  \ und unter Ber\xFCcksichtigung der rechtlichen Voraussetzungen ergeht folgender\
  \ Bescheid:\n\nTenor:\n1. Sie sind verpflichtet, das Fachwerkhaus in Neuried, Lange\
  \ Stra\xDFe 12, mit Biberschwanz-Dachziegeln zu reparieren.\n2. Die Reparaturanordnung\
  \ ist sofort vollziehbar.\n\nBegr\xFCndung:\nDas Fachwerkhaus ist ein Kulturdenkmal\
  \ im Sinne von \xA7 2 Abs. 1 DSchG, da dessen Erhaltung aus heimatgeschichtlichen\
  \ Gr\xFCnden ein \xF6ffentliches Interesse besteht. Durch den Sturm wurden ca. 50\
  \ Biberschwanz-Dachziegel abgedeckt, wodurch eine Gef\xE4hrdung des Denkmals vorliegt.\n\
  \nAls Pflichtige kommen sowohl Sie als auch Ihr Bruder Georg Konrad in Betracht.\
  \ Sie sind nach \xA7 7 Abs. 1 Satz 1 DSchG und \xA7 7 PolG als Eigent\xFCmer des\
  \ Fachwerkhauses verpflichtet, von dem eine Gefahr ausgeht. Ihr Bruder Georg Konrad\
  \ ist ebenfalls Eigent\xFCmer des Fachwerkhauses und somit nach denselben Vorschriften\
  \ pflichtig.\n\nDie Anordnung der BSD ist verh\xE4ltnism\xE4\xDFig und ermessensgerecht,\
  \ da eine kosteng\xFCnstigere Reparatur mit Eternitplatten nicht geeignet ist, die\
  \ Denkmalanforderungen zu erf\xFCllen. Der Vorteil f\xFCr die Allgemeinheit durch\
  \ die Ansehnlichkeit des Denkmals rechtfertigt den finanziellen Nachteil f\xFCr\
  \ den Eigent\xFCmer.\n\nEine privatrechtliche Unm\xF6glichkeit liegt nicht vor,\
  \ da Sie ohne die Mitwirkung Ihres Bruders handeln k\xF6nnen und die Ma\xDFnahme\
  \ als notwendige Erhaltungsma\xDFnahme anzusehen ist.\n\nDie Anordnung ist bestimmt\
  \ genug formuliert und entspricht den formellen Voraussetzungen.\n\nRechtsbehelfsbelehrung:\n\
  Gegen die Dachdeckungsanordnung k\xF6nnen Sie innerhalb eines Monats nach Bekanntgabe\
  \ Widerspruch einlegen (\xA7 37 Abs. 6 LVwVfG, \xA7 70 VwGO). Gegen die Anordnung\
  \ der sofortigen Vollziehung k\xF6nnen Sie den Antrag auf Wiederherstellung der\
  \ aufschiebenden Wirkung beim Verwaltungsgericht stellen (\xA7 80 Abs. 5 VwGO).\n\
  \nUnterschrift mit Gru\xDFformel:\nMit freundlichen Gr\xFC\xDFen,\n\n[Name des Sachbearbeiters]"
