erstellt: false
message_str: "Sehr geehrter Herr Graeter,\n\nSie haben einen Antrag auf Erlaubnis\
  \ zur Er\xF6ffnung einer Musikkneipe in den leer stehenden R\xE4umen der ehemaligen\
  \ Gastst\xE4tte \"Walfisch\" in der Hauptstra\xDFe in Kehl gestellt. Bei der Durchsicht\
  \ der Unterlagen wurden einige M\xE4ngel festgestellt, die im Folgenden erl\xE4\
  utert werden.\n\nDie Stadt Kehl ordnet an, dass Sie folgende Voraussetzungen erf\xFC\
  llen m\xFCssen, um die Erlaubnis zur Er\xF6ffnung der Musikkneipe zu erhalten:\n\
  \n1. Sie m\xFCssen eine Bescheinigung \xFCber lebensmittelrechtliche Kenntnisse\
  \ gem\xE4\xDF \xA7 4 GastG vorlegen.\n\n2. Die bauordnungsrechtlichen Voraussetzungen,\
  \ insbesondere die Anzahl der Urinale auf der Herrentoilette gem\xE4\xDF den entsprechenden\
  \ Kapazit\xE4tsberechnungen, m\xFCssen erf\xFCllt sein.\n\n3. Die Stadt Kehl empfiehlt,\
  \ Ma\xDFnahmen zur L\xE4rmminderung zu ergreifen, um die Anwohner vor L\xE4rmbel\xE4\
  stigungen zu sch\xFCtzen.\n\nGem\xE4\xDF \xA7 2 GastG ist die geplante Musikkneipe\
  \ erlaubnispflichtig. Um die Gesundheit der G\xE4ste zu sch\xFCtzen, m\xFCssen die\
  \ bauordnungsrechtlichen Voraussetzungen und die Bescheinigung \xFCber lebensmittelrechtliche\
  \ Kenntnisse erf\xFCllt sein.\n\nBei der Besichtigung der R\xE4ume durch den st\xE4\
  dtischen Bauaufseher wurden M\xE4ngel festgestellt, insbesondere die Anzahl der\
  \ Urinale auf der Herrentoilette entspricht nicht den entsprechenden Kapazit\xE4\
  tsberechnungen.\n\nEs besteht auch die M\xF6glichkeit von L\xE4rmbel\xE4stigungen\
  \ in der Umgebung, die gem\xE4\xDF \xA7 5 GastG zu ber\xFCcksichtigen sind.\n\n\
  Die Anordnung der Stadt Kehl ist verh\xE4ltnism\xE4\xDFig und ermessensgerecht,\
  \ da die bauordnungsrechtlichen Voraussetzungen und die Bescheinigung \xFCber lebensmittelrechtliche\
  \ Kenntnisse erf\xFCllt sein m\xFCssen, um die Gesundheit der G\xE4ste zu sch\xFC\
  tzen. Auch die Ber\xFCcksichtigung der L\xE4rmbel\xE4stigung ist notwendig, um die\
  \ Interessen der Anwohner zu wahren.\n\nGegen diese Anordnung k\xF6nnen Sie innerhalb\
  \ eines Monats nach Bekanntgabe Widerspruch einlegen (\xA7 70 VwGO). Der Widerspruch\
  \ ist schriftlich oder zur Niederschrift bei der Stadt Kehl, Hauptstra\xDFe 1, 77694\
  \ Kehl, einzulegen.\n\nMit freundlichen Gr\xFC\xDFen,\n\n[Unterschrift]"
