chatHist:
  - init
erstellt: false
message_str: ''
sachverhalt: ''
tutorial: "Mit diesem Chatbot k\xF6nnen sie einen Bescheid erstellen, in dem Sie einen\
  \ Sachverhalt \xFCber den Hochladen Button hinzuf\xFCgen. Daraufhin wird Ihnen automatisch\
  \ ein Bescheid generiert. Dieser wird Ihnen als Chatnachricht zur\xFCckgegeben,\
  \ sobald er erstellt wurde. Diesen k\xF6nnen Sie noch weiter bearbeiten und Fragen\
  \ dazu stellen, in dem Sie dem Chatbot \xC4nderungsw\xFCnsche mitteilen. Desweiteren\
  \ k\xF6nnen Sie auch allgemeine Fragen stellen oder auch Fragen zum Inhalt des hochgeladenen\
  \ Sachverhalts. Sobald sie zufrieden mit dem generierten Bescheid sind, k\xF6nnen\
  \ sie durch das Dr\xFCcken des Herunterladen Buttons den Bescheid als doc-Datei\
  \ anfordern, woraufhin dieser heruntergeladen wird. Um mehrere Chats zu \xF6ffnen,\
  \ klicken Sie auf den Button Neuer Chat. "
