erstellt: false
message_str: "Einleitung:\n\nSehr geehrter Herr Graeter,\n\nSie haben einen Antrag\
  \ auf Erteilung einer Erlaubnis f\xFCr eine Musikkneipe in den R\xE4umen der ehemaligen\
  \ Gastst\xE4tte \"Walfisch\" in Kehl gestellt. Nach Pr\xFCfung des Sachverhalts\
  \ und der rechtlichen Voraussetzungen wird Ihnen hiermit die Erlaubnis unter bestimmten\
  \ Bedingungen erteilt.\n\nTenor:\n\nDie Erlaubnis f\xFCr den Betrieb einer Musikkneipe\
  \ in den R\xE4umen der ehemaligen Gastst\xE4tte \"Walfisch\" in Kehl wird unter\
  \ der Bedingung erteilt, dass die Herrentoilette entsprechend umgebaut wird. Bei\
  \ L\xE4rmbel\xE4stigungen in der Umgebung m\xFCssen Ma\xDFnahmen ergriffen werden.\n\
  \nBegr\xFCndung:\n\nDie Erlaubniserteilung erfolgt aufgrund der rechtlichen Voraussetzungen\
  \ des \xA7 12 GastG. Die Erlaubnispflicht ergibt sich aus \xA7 2 GastG. Die Zuverl\xE4\
  ssigkeit des Antragstellers ist gem\xE4\xDF \xA7 4 GastG gepr\xFCft worden und die\
  \ Sachkunde gem\xE4\xDF \xA7 5 GastG.\n\nDie Stadt Kehl hat gem\xE4\xDF \xA7 12\
  \ GastG ein Ermessen, das nach \xA7 40 LVwVfG ausge\xFCbt wird. Die Erlaubniserteilung\
  \ ist verh\xE4ltnism\xE4\xDFig und ermessensgerecht, wenn die materiellen Voraussetzungen\
  \ erf\xFCllt sind und die \xF6ffentlichen Interessen nicht entgegenstehen.\n\nEs\
  \ k\xF6nnte eine Unm\xF6glichkeit vorliegen, wenn die Herrentoilette nicht den Anforderungen\
  \ entspricht. In diesem Fall k\xF6nnte die Erlaubnis nur unter der Bedingung erteilt\
  \ werden, dass die Toilette entsprechend umgebaut wird.\n\nDie Erlaubnis ist bestimmt\
  \ genug formuliert, um den Anforderungen des \xA7 37 LVwVfG zu gen\xFCgen.\n\nRechtsbehelfsbelehrung:\n\
  \nGegen diesen Bescheid kann innerhalb eines Monats nach Bekanntgabe Widerspruch\
  \ eingelegt werden (\xA7 70 VwGO). Der Widerspruch ist schriftlich oder zur Niederschrift\
  \ beim Amt f\xFCr \xF6ffentliche Ordnung der Stadt Kehl, Hauptstra\xDFe 1, 77694\
  \ Kehl, einzulegen.\n\nUnterschrift mit Gru\xDFformel:\n\nMit freundlichen Gr\xFC\
  \xDFen\n\n[Name und Funktion des Unterzeichners]"
