erstellt: false
message_str: "Einleitung:\nSehr geehrter Herr Konrad,\n\nnach Pr\xFCfung des Sachverhalts\
  \ und unter Ber\xFCcksichtigung der rechtlichen Voraussetzungen ergeht folgender\
  \ Bescheid:\n\nTenor:\n1. Sie sind als Eigent\xFCmer des Fachwerkhauses in Neuried,\
  \ Lange Stra\xDFe 12, verpflichtet, das Dach mit Biberschwanz-Dachziegeln zu reparieren.\n\
  2. Die Reparaturanordnung ist sofort vollziehbar.\n\nBegr\xFCndung:\nDas Fachwerkhaus\
  \ stellt ein Kulturdenkmal dar, da es aus heimatgeschichtlichen Gr\xFCnden ein \xF6\
  ffentliches Interesse an seiner Erhaltung gibt (\xA7 2 Abs. 1 DSchG). Durch den\
  \ Sturm wurden ca. 50 Biberschwanz-Dachziegel abgedeckt, wodurch eine Gef\xE4hrdung\
  \ des Denkmals vorliegt. Die Reparaturanordnung st\xFCtzt sich auf \xA7 1 Abs. 1\
  \ in Verbindung mit \xA7 7 Abs. 1 Satz 1 DSchG sowie \xA7 7 PolG.\n\nAls Eigent\xFC\
  mer des Fachwerkhauses sind Sie verpflichtet, die Reparatur durchzuf\xFChren. Eine\
  \ kosteng\xFCnstigere Reparatur mit Eternitplatten ist nicht geeignet, die Denkmalanforderungen\
  \ zu erf\xFCllen. Die Anordnung der BSD ist verh\xE4ltnism\xE4\xDFig und ermessensgerecht,\
  \ da der Vorteil f\xFCr die Allgemeinheit durch die Ansehnlichkeit des Denkmals\
  \ den finanziellen Nachteil f\xFCr den Eigent\xFCmer \xFCberwiegt.\n\nEine privatrechtliche\
  \ Unm\xF6glichkeit liegt nicht vor, da Sie ohne die Mitwirkung Ihres Bruders Georg\
  \ Konrad handeln k\xF6nnen. Eine Mitbestimmungspflicht nach \xA7 2038 Abs. 1 Satz\
  \ 1 BGB entf\xE4llt, da die Reparaturanordnung als notwendige Erhaltungsma\xDFnahme\
  \ anzusehen ist (\xA7 2038 Abs. 1 Satz 2 Halbsatz 2 BGB).\n\nRechtsbehelfsbelehrung:\n\
  Gegen die Reparaturanordnung k\xF6nnen Sie innerhalb eines Monats nach Bekanntgabe\
  \ Widerspruch einlegen (\xA7 37 Abs. 6 LVwVfG). Gegen die Anordnung der sofortigen\
  \ Vollziehung k\xF6nnen Sie den Antrag auf Wiederherstellung der aufschiebenden\
  \ Wirkung beim Verwaltungsgericht Freiburg stellen (\xA7 80 Abs. 5 VwGO).\n\nUnterschrift\
  \ mit Gru\xDFformel:\nMit freundlichen Gr\xFC\xDFen,\n\n[Name des Sachbearbeiters]"
