erstellt: false
message_str: "Einleitung:\n\nLandratsamt Ortenaukreis\nHerrn Franz Konrad\nSachbearbeiter\n\
  \nReparatur Ihres Fachwerkhauses in Neuried, Lange Stra\xDFe 12\n\nSehr geehrter\
  \ Herr Konrad,\n\nhiermit ergeht folgender Bescheid:\n\nTenor:\n\n1. Sie sind verpflichtet,\
  \ das Fachwerkhausdach mit Biberschwanz-Dachziegeln zu reparieren.\n2. Die Reparaturanordnung\
  \ ist sofort vollziehbar.\n\nBegr\xFCndung:\n\nSie sind als Forstrat zusammen mit\
  \ Ihrem Bruder, dem Studenten Georg Konrad, Eigent\xFCmer des o.g. Fachwerkhauses.\
  \ Das Haus stammt aus dem Jahre 1865 und geh\xF6rt zu den wenigen voll erhaltenen\
  \ Exemplaren seiner Art am Oberrhein. Durch einen Sturm wurden ca. 50 Biberschwanz-Dachziegel\
  \ abgedeckt, wodurch das Fachwerkhausdach besch\xE4digt wurde.\n\nDas Fachwerkhaus\
  \ ist ein Kulturdenkmal, da es nach \xA7 2 Abs. 1 DSchG ein \xF6ffentliches Erhaltungsinteresse\
  \ aus heimatgeschichtlichen Gr\xFCnden gibt. Das Kulturdenkmal ist gef\xE4hrdet,\
  \ da durch das beeintr\xE4chtigte Erscheinungsbild bereits ein Schaden entstanden\
  \ ist.\n\nDie Reparaturanordnung st\xFCtzt sich auf \xA7 1 Abs. 1 in Verbindung\
  \ mit \xA7 7 Abs. 1 DSchG. Danach k\xF6nnen wir Ma\xDFnahmen anordnen, wenn ein\
  \ Kulturdenkmal gef\xE4hrdet ist. Die Anordnung der BSD ist verh\xE4ltnism\xE4\xDF\
  ig und ermessensgerecht, da eine kosteng\xFCnstigere Reparatur mit Eternitplatten\
  \ nicht geeignet ist, die Denkmalanforderungen zu erf\xFCllen. Der Vorteil f\xFC\
  r die Allgemeinheit durch die Ansehnlichkeit des Denkmals rechtfertigt den finanziellen\
  \ Nachteil f\xFCr den Eigent\xFCmer (F.K.).\n\nAls Pflichtige kommen sowohl F.K\
  \ als auch G.K in Betracht. F.K k\xF6nnte pflichtig sein sinngem\xE4\xDF \xA7 7\
  \ Abs. 1 Satz 1 DSchG und \xA7 7 PolG, da er Eigent\xFCmer einer Sache ist, von\
  \ deren Zustand eine Gefahr ausgeht. Der G.K ist ebenfalls Eigent\xFCmer des Fachwerkhauses\
  \ und somit nach denselben Vorschriften pflichtig.\n\nEs besteht keine Problematik\
  \ im Sinne des \xA7 21 LVwVfg. Nach \xA73 Abs. 4 DSchG muss das Landesamt f\xFC\
  r Denkmalpflege angeh\xF6rt werden. Nach \xA7 28 Abs. 1 LVwVfG ist F.K und G.K die\
  \ Gelegenheit zur \xC4u\xDFerung zu geben.\n\nRechtsbehelfsbelehrung:\n\nGegen die\
  \ Dachdeckungsanordnung k\xF6nnen Sie innerhalb eines Monats nach Bekanntgabe bei\
  \ dem Landratsamt Ortenaukreis, Badstra\xDFe 22, 77652 Offenburg Widerspruch einlegen.\
  \ Gegen die Anordnung der sofortigen Vollziehung k\xF6nnen Sie den Antrag auf Wiederherstellung\
  \ der aufschiebenden Wirkung beim Verwaltungsgericht Freiburg, Herbstburgerstra\xDF\
  e 115, 79104 Freiburg stellen.\n\nUnterschrift mit Gru\xDFformel:\n\nMit freundlichen\
  \ Gr\xFC\xDFen\n\nLandratsamt Ortenaukreis\nSachbearbeiter"
