erstellt: false
message_str: "Stadt Kehl\nAmt f\xFCr \xF6ffentliche Ordnung\nHauptstra\xDFe 1\n77694\
  \ Kehl\n\nHerrn Michael Graeter\nMusterstra\xDFe 1\n12345 Musterstadt\n\nBetreff:\
  \ Antrag auf Erlaubnis zum Betrieb einer Musikkneipe in der ehemaligen Gastst\xE4\
  tte \"Walfisch\" in der Hauptstra\xDFe in Kehl\n\nSehr geehrter Herr Graeter,\n\n\
  hiermit teilen wir Ihnen mit, dass Ihr Antrag auf Erlaubnis zum Betrieb einer Musikkneipe\
  \ in der ehemaligen Gastst\xE4tte \"Walfisch\" in der Hauptstra\xDFe in Kehl vorerst\
  \ nicht genehmigt werden kann.\n\nTenor:\n\nDie Erlaubnis zum Betrieb einer Musikkneipe\
  \ in der ehemaligen Gastst\xE4tte \"Walfisch\" in der Hauptstra\xDFe in Kehl wird\
  \ vorerst nicht erteilt.\n\nBegr\xFCndung:\n\nGem\xE4\xDF \xA7 2 Abs. 1 GastG ist\
  \ f\xFCr den Betrieb einer Gastst\xE4tte eine Erlaubnis erforderlich. Bei Durchsicht\
  \ der Unterlagen haben wir festgestellt, dass die Bescheinigung \xFCber lebensmittelrechtliche\
  \ Kenntnisse fehlt. Dies stellt eine Tatbestandsvoraussetzung gem\xE4\xDF \xA7 4\
  \ GastG dar.\n\nDes Weiteren konnte bei der Besichtigung der R\xE4ume durch den\
  \ st\xE4dtischen Bauaufseher auf der Herrentoilette nur eine unzureichende Anzahl\
  \ von Urinalen registriert werden, obwohl nach entsprechenden Kapazit\xE4tsberechnungen\
  \ drei vorhanden sein m\xFCssen. Auch dies stellt eine Tatbestandsvoraussetzung\
  \ gem\xE4\xDF \xA7 4 GastG dar.\n\nZudem haben wir aus Erfahrung mit \xE4hnlichen\
  \ Kneipen in der Umgebung Bedenken hinsichtlich m\xF6glicher L\xE4rmbel\xE4stigungen.\
  \ Die Stadt Kehl hat gem\xE4\xDF \xA7 4 GastG ein Ermessen, das nach \xA7 40 LVwVfG\
  \ ausge\xFCbt wird. Bevor wir Ihre Erlaubnis erteilen k\xF6nnen, m\xFCssen diese\
  \ M\xE4ngel behoben werden.\n\nWir bitten Sie daher, uns eine Bescheinigung \xFC\
  ber lebensmittelrechtliche Kenntnisse sowie eine Best\xE4tigung \xFCber die Erweiterung\
  \ der Anzahl der Urinale auf der Herrentoilette vorzulegen.\n\nErmessen:\n\nDie\
  \ Stadt Kehl hat gem\xE4\xDF \xA7 4 GastG ein Ermessen bei der Erteilung der Erlaubnis.\
  \ Dabei ist insbesondere zu ber\xFCcksichtigen, ob der Antragsteller die erforderliche\
  \ Zuverl\xE4ssigkeit besitzt und die f\xFCr den Betrieb der Gastst\xE4tte erforderlichen\
  \ R\xE4umlichkeiten, Einrichtungen und Ger\xE4te vorhanden sind. Auch die Erfahrungen\
  \ mit \xE4hnlichen Kneipen in der Umgebung und die zu bef\xFCrchtenden L\xE4rmbel\xE4\
  stigungen sind in die Ermessensentscheidung einzubeziehen.\n\nRechtsbehelfsbelehrung:\n\
  \nGegen diesen Bescheid k\xF6nnen Sie innerhalb eines Monats nach Bekanntgabe Widerspruch\
  \ einlegen. Der Widerspruch ist schriftlich oder zur Niederschrift beim Amt f\xFC\
  r \xF6ffentliche Ordnung der Stadt Kehl, Hauptstra\xDFe 1, 77694 Kehl, einzulegen.\n\
  \nMit freundlichen Gr\xFC\xDFen\n\nIm Auftrag\n\n[Unterschrift]\n\n[Name des Sachbearbeiters]"
